# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R
cache: packages
sudo: required
dist: trusty
addons:
  apt:
    packages:
      - libproj-dev
      - libgdal-dev
      - libgeos-dev
      - libv8-3.14-dev
      - libudunits2-dev

